### ISSUE TITLE
DELAYBIND deprecation error

### ISSUE THREAD

**Issue by CarloLucibello** [seebk/LaTeXText#11]
Hi,
unfortunately, I see the following error when trying to render the tex input:
```
 *** WARNING - the DELAYBIND command has been deprecated, and will be
               removed in the next version. For now you can restore
               the behaviour by using -dREALLYDEALYBIND but if you
               require continued use of this command you should contact
               the Ghostscript developers. Commercial customers of
               Artifex should email their support contact, free users
               are encouraged to talk to us on the #ghostscript IRC
               channel on irc.freenode.net.

Unrecoverable error: undefined in DELAYBIND

PostScript/PDF Interpreter finished. Return status 65280 executed command : /usr/bin/gs -q -dDELAYBIND -dWRITESYSTEMDICT -dNODISPLAY -dNOEPS "/tmp/psinB4DjX4"

The interpreter seems to have failed, cannot proceed !

Traceback (most recent call last):
  File "eqtexsvg.py", line 160, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "eqtexsvg.py", line 154, in effect
    svg_open(self, svg_file)
  File "eqtexsvg.py", line 81, in svg_open
    doc = inkex.etree.parse(filename)
  File "src/lxml/etree.pyx", line 3444, in lxml.etree.parse (src/lxml/etree.c:83188)
  File "src/lxml/parser.pxi", line 1834, in lxml.etree._parseDocument (src/lxml/etree.c:120760)
  File "src/lxml/parser.pxi", line 1860, in lxml.etree._parseDocumentFromURL (src/lxml/etree.c:121107)
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDocFromFile (src/lxml/etree.c:120015)
  File "src/lxml/parser.pxi", line 1161, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/etree.c:114564)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107741)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109450)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108304)
  File "/tmp/inkscape-eR0BaG/eq.svg", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```
I'm on manjaro linux, and all packages are updated to their most recent version. Do we need `DELAYBIND` in the  `gs` call?

**Comment by seebk** [comment]
I think your are using [EqTeXSVG](https://www.julienvitard.eu/en/eqtexsvg_en.html) and not the extension from this GitHub project....

**Comment by CarloLucibello** [comment]
ops, I'm sorry, I installed so many extensions in recent years. Still, LaTeXText is node working, the renderend layer is empty, log saying `0 text nodes were found` even though I have two text boxes with `$\frac{1}{2}$` and `$$\frac{1}{2}$$` respectively. Sorry if I'm doing something silly

**Comment by seebk** [comment]
Maybe it's related to this? -> https://github.com/seebk/LaTeXText/issues/5#issuecomment-352401191

**Comment by seebk** [comment]
No more feedback from the reporter, will close this.
