### ISSUE TITLE
 'ascii' codec can't encode character u'\xa0' in position 291

### ISSUE THREAD

**Issue by pswpswpsw** [seebk/LaTeXText#18]
I have no idea what is going on. It seems like there is an invalid character \xa0?

# error
Traceback (most recent call last):
  File "latextext_gtk3.py", line 158, in on_btnApply_clicked
    self.run_callback()
  File "/home/shawnpan/.config/inkscape/extensions/latextext.py", line 475, in run
    rendergroup = lat2svg.render(latex_string, self.options.preamble, self.options.packages, self.options.fontsize, self.options.scale)
  File "/home/shawnpan/.config/inkscape/extensions/latextext.py", line 563, in render
    f_tex.write(texwrapper)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 291: ordinal not in range(128)

**Comment by pswpswpsw** [comment]
I solved the problem by deleting **a space text object** in my plot.
