### ISSUE TITLE
Runtime error on new files. Works with files where applied before

### ISSUE THREAD

**Issue by MMLeo** [seebk/LaTeXText#23]
LaTexText worked fine just yesterday. It still does in the files I used it on yesterday.
Should I create a new drawing though and try to run it with the same settings as in the other files it does create a new layer but no text and I get the error message below. I also noticed, that should I copy paste an already Latex-transformed text object in my new drawing, it works perfectly fine again, with the settings presented down below that is. But would I change the font size for example, it again doesnt work. 

Command "pdflatex c:\users\user\appdata\local\temp\tmp5efh7e\tmp.tex -interaction=nonstopmode -halt-on-error" failed (code 1): 

 This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9 64-bit)

entering extended mode

(c:/users/user/appdata/local/temp/tmp5efh7e/tmp.tex

LaTeX2e <2015/01/01> patch level 2

Babel <3.9m> and hyphenation patterns for 69 languages loaded.

("C:\Program Files\MiKTeX 2.9\tex\latex\base\article.cls"

Document Class: article 2014/09/29 v1.4h Standard LaTeX document class

("C:\Program Files\MiKTeX 2.9\tex\latex\base\size10.clo"))

("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.sty"

("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\keyval.sty")

("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifpdf.sty")

("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifvtex.sty")

("C:\Program Files\MiKTeX 2.9\tex\generic\ifxetex\ifxetex.sty")

("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.cfg"))

("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsmath.sty"

For additional information on amsmath, use the `?' option.

("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amstext.sty"

("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsgen.sty"))

("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsbsy.sty")

("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsopn.sty"))

("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\amssymb.sty"

("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\amsfonts.sty"))

No file tmp.aux.

*geometry* driver: auto-detecting

*geometry* detected driver: pdftex

("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\umsa.fd")

("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\umsb.fd")

! Missing $ inserted.

<inserted text> 

                $

l.13 

     

!  ==> Fatal error occurred, no output PDF file produced!

Transcript written on tmp.log.

Traceback (most recent call last):
  File "latextext_gtk3.py", line 158, in on_btnApply_clicked
    self.run_callback()
  File "latextext.py", line 475, in run
    rendergroup = lat2svg.render(latex_string, self.options.preamble, self.options.packages, self.options.fontsize, self.options.scale)
  File "latextext.py", line 580, in render
    raise RuntimeError()
RuntimeError
![Popup](https://user-images.githubusercontent.com/49960395/56742062-59aeb580-6774-11e9-98a1-94ca9f158447.png)
![Settings](https://user-images.githubusercontent.com/49960395/56742063-59aeb580-6774-11e9-9ae3-16b9856df667.png)

Installed Inkscape 0.92.4 and MiKTeX 2.9

**Comment by Visperad22** [comment]
I have the same problem. Did you solve it?

**Comment by MMLeo** [comment]
Back then I was trying to copy pre-written Tex-Code into the interface where you change text, that didn't work. After I rewrote it it worked though.
It also doesn't convert text fields that has a break in it I think

**Comment by jssprz** [comment]
@Visperad22 Did the @MMLeo solution work for you?

**Comment by Visperad22** [comment]
I noticed another problem related to this issue. It was about the MiKTex new release. Somehow the new release did not automatically install some of the fonts packages so I had to manually install the, After that, I did not have the problem. Please see this one on the issue:
https://github.com/MiKTeX/miktex-packaging/issues/112#issuecomment-577104722

**Comment by tongliang11** [comment]
I get the same error message.
First time user, the extension has never worked.
Tried to install font packages from MikTex, but it's still not working.
Does anyone know what's the problem? Thanks in advance.
