### ISSUE TITLE
Support for TexLive?

### ISSUE THREAD

**Issue by yagars** [seebk/LaTeXText#28]
Try as I might, I cannot get MikTeX to work on my system anymore. I use TexLive now. The LaTeXText extension is great. Is there any way I can point InkScape to pdfLatex in my TexLive install? Thanks in advance.

**Comment by yagars** [comment]
I just noticed that you already discussed this here:
https://github.com/seebk/LaTeXText/issues/20#issuecomment-433637121

How can I include pdflatex.exe in the PATH? I'm not sure which path you are referring to.

**Comment by seebk** [comment]
There's an environment variable PATH that has to include the path of the TexLive folder where the pdflatex.exe is located. Have a look [here](https://docs.alfresco.com/4.2/tasks/fot-addpath.html) to see how to set up that path on Windows.

**Comment by yagars** [comment]
Great, thanks. I was able to add the folder containing pdflatex.exe to the system variable PATH but I still get the following error in Inkscape:


Command "pdflatex c:\users\myname~1.myname\appdata\local\temp\tmpe1hsdq\tmp.tex -interaction=nonstopmode -halt-on-error" failed (code 1): 

 This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/W32TeX) (preloaded format=pdflatex)

 restricted \write18 enabled.

entering extended mode

! I can't find file `c:/users/myname'.

<to be read again> 

                   \protect 

<*> c:/users/myname~

                  1.myname/appdata/local/temp/tmpe1hsdq/tmp.tex -interaction=no...



(Press Enter to retry, or Control-Z to exit)

Please type another input file name: 

! Emergency stop.

<to be read again> 

                   \protect 

<*> c:/users/myname~

                  1.myname/appdata/local/temp/tmpe1hsdq/tmp.tex -interaction=no...



!  ==> Fatal error occurred, no output PDF file produced!

Transcript written on texput.log.



Traceback (most recent call last):
  File "latextext_gtk3.py", line 158, in on_btnApply_clicked
    self.run_callback()
  File "latextext.py", line 475, in run
    rendergroup = lat2svg.render(latex_string, self.options.preamble, self.options.packages, self.options.fontsize, self.options.scale)
  File "latextext.py", line 580, in render
    raise RuntimeError()
RuntimeError

**Comment by yagars** [comment]
After more investigation, it seems like one of the functions is hanging on the fact that my Windows user name has a dot (.) in it when trying to access tmpe1hsdq/tmp.tex. Do you have some advice for me? Thanks.

**Comment by yagars** [comment]
Hi @seebk .
Do you maybe have an idea to help solve my problem?
Thanks in advance.
