### ISSUE TITLE
Compilation fails with "GUI framework cannot be initialized" pdflatex log report

### ISSUE THREAD

**Issue by jcstraccia** [seebk/LaTeXText#31]
I just upgraded to windows 10 and after reinstalling MikTex 2.9, Inkspace 0.92.4 and LaTeXText I'm unable to compile Latex script in Inkscape. After I click Apply on the LaTeXText window the following error window opens up and no new layer is created:
Inkscape has received additional data from the script executed.  The script did not return an error, but this may indicate the results will not be as expected.

This is the log from LaTeXText :
Command "pdflatex c:\users\joseph\appdata\local\temp\tmpuwy7zf\tmp.tex -interaction=nonstopmode -halt-on-error" failed (code 1): 

 This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 2.9.7300 64-bit)

entering extended mode

(c:/Users/Joseph/AppData/Local/Temp/tmpuwy7zf/tmp.tex

LaTeX2e <2020-02-02> patch level 5

L3 programming layer <2020-03-06>

("C:\Users\Joseph\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\article.cls"

Document Class: article 2019/12/20 v1.4l Standard LaTeX document class

("C:\Users\Joseph\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\size10.clo")

)

Sorry, but pdflatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\Joseph\AppData\Local\MiKTeX\2.9\miktex\log\pdflatex.log

Traceback (most recent call last):
  File "latextext_gtk3.py", line 158, in on_btnApply_clicked
    self.run_callback()
  File "latextext.py", line 475, in run
    rendergroup = lat2svg.render(latex_string, self.options.preamble, self.options.packages, self.options.fontsize, self.options.scale)
  File "latextext.py", line 580, in render
    raise RuntimeError()
RuntimeError

The pdflatex log reads:
2020-03-19 13:38:28,453-0600 INFO  pdflatex - starting with command line: pdflatex c:\users\joseph\appdata\local\temp\tmpuwy7zf\tmp.tex -interaction=nonstopmode -halt-on-error
2020-03-19 13:38:28,469-0600 INFO  pdflatex - allowing known shell commands
2020-03-19 13:38:28,469-0600 INFO  pdflatex - enabling input (output) from (to) processes
2020-03-19 13:38:28,640-0600 FATAL pdflatex - GUI framework cannot be initialized.
2020-03-19 13:38:28,640-0600 FATAL pdflatex - Info: 
2020-03-19 13:38:28,640-0600 FATAL pdflatex - Source: Libraries\MiKTeX\UI\Qt\mikuiqt.cpp
2020-03-19 13:38:28,640-0600 FATAL pdflatex - Line: 77
2020-03-19 13:38:28,640-0600 INFO  pdflatex - finishing with exit code 1

Is this really a problem with MiKTeX? MiKTeX is working fine with Texmaker. Also I'm running the same versions of all of these programs on my laptop with windows 10 and don't have this problem. Any help would be much appreciated.

Thanks,
Joseph

**Comment by jcstraccia** [comment]
Well if anyone else runs into this issue the solution is to open the MiKTeX Console which is in the start menu programs list and under the settings tab select "Always install missing packages on-the-fly".

**Comment by jpeter3** [comment]
Had the same problem, this solution worked for me also! Thx :)

**Comment by proteomis** [comment]
I had the same problem and the solution worked for me too. Thanks a lot.

**Comment by helenlwaite** [comment]
Worked for me too, thanks!

**Comment by arkansoap** [comment]
thanks a lot !

**Comment by h4df13ld** [comment]
Worked for me too. Thanks!
