### ISSUE TITLE
Rendered layer empty after RuntimeError

### ISSUE THREAD

**Issue by stribor14** [seebk/LaTeXText#33]
Inkscape 0.92.5 (2060ec1f9f, 2020-04-08)
Ubuntu Noetic
```
Command "pdflatex /tmp/tmp77PlQG/tmp.tex -interaction=nonstopmode -halt-on-error" > failed: [Errno 2] No such file or directory

Traceback (most recent call last):
  File "latextext_gtk3.py", line 158, in on_btnApply_clicked
    self.run_callback()
  File "/home/mirko/.config/inkscape/extensions/latextext.py", line 475, in run
    rendergroup = lat2svg.render(latex_string, self.options.preamble, self.options.packages, self.options.fontsize, self.options.scale)
  File "/home/mirko/.config/inkscape/extensions/latextext.py", line 580, in render
    raise RuntimeError()
RuntimeError
```

**Comment by stribor14** [comment]
Sorry, even after I've searched and opened up a new issue, I've found that #23 already contains the same error message

**Comment by stribor14** [comment]
Issue #30 solved it for me!
